Issue #336 Replacing Utils.move_file with Shutil.move function
physiopy/phys2bids pull request #337
Opened 2020-10-28 07:28 UTC by jiyoungsin

Closes # 336

## Proposed Changes

  - Removed the function and associated tests DONE.
  - Remove the item from the API docs page NONE.
  - Replace the function call throughout the package DONE.

2020-10-28 08:03 UTC, eurunuela commented
Thank you so much @jiyoungsin !

I think we can just remove the function and the unit test. The function is not used anywhere in the code but the unit test anyway.

2020-10-28 08:52 UTC, smoia requested changes
Hey @jiyoungsin , thank you for your first contribution!
I know it might look like a buzzkill now because in the end we should remove the function, but cleaning up code is a nice contribution nonetheless!
If you want to try again with a good first issue that is a tad more challenging, why don't you take #334 or #335?

We also need to slightly retouch the PR: I'm going to assign the correct label for your contribution, but in the meantime, could you slightly change the title to make it more "changelog ready"? You can have a look at [this release](https://github.com/physiopy/phys2bids/tree/2.2.0) for _a lot_ of examples, or in general at the release page.
Something like "Remove redundant utility function `move_file()`" could work.

Finally, the tests are failing (bad sign), but as soon as you address the changes I'm suggesting I'm sure it will work!

2020-10-28 08:52 UTC, smoia commented on phys2bids/tests/test_utils.py
>          pass
I can't comment at the right line, but I would equally remove this chunk of code (lines 62-70)

2020-11-10 21:59 UTC, smoia commented
@jiyoungsin let us know if you need any help!

2020-11-10 23:55 UTC, jiyoungsin commented
hey @smoia thanks again for waiting around for me, however, I have a lot of school work I must catch up on. Can you please assign this to someone else?

2020-11-11 08:04 UTC, eurunuela commented
I assigned it to myself but been quite busy in the last few weeks. I'm thinking that this could be a good way to start working on phys2bids for some of the newcomers from Brainhack Donostia. What do you think @smoia ?

2020-11-11 08:19 UTC, smoia commented
Indeed!

2020-11-11 10:19 UTC, closed without merging

2020-11-29 19:16 UTC, smoia commented
<!-- GITHUB_RELEASE COMMENT: released -->
:rocket: Issue was released in [`2.3.0`](https://github.com/physiopy/phys2bids/releases/tag/2.3.0) :rocket: